

# make the subdir first
SHELL :=/bin/bash
CXX = g++
FLAG = -O3

all:
	# --- CUBE_To_SURF ---- #
	$(CXX) CUBE_To_SURF.cpp $(FLAG) -o CUBE_To_SURF
	mv CUBE_To_SURF ../util


# clean all the temp files
clean:

